//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.omniscient.ca/foundation/applicationConfiguration.xsd")]
[System.Xml.Serialization.XmlRootAttribute("foundation.application", Namespace="http://schemas.omniscient.ca/foundation/applicationConfiguration.xsd", IsNullable=false)]
public partial class ApplicationConfiguration {
    
    private ServicesConfiguration itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("services")]
    public ServicesConfiguration Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.omniscient.ca/foundation/applicationConfiguration.xsd")]
public partial class ServicesConfiguration {
    
    private ServiceDefinition[] serviceDefinitionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("serviceDefinition")]
    public ServiceDefinition[] serviceDefinition {
        get {
            return this.serviceDefinitionField;
        }
        set {
            this.serviceDefinitionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.omniscient.ca/foundation/applicationConfiguration.xsd")]
public partial class ServiceDefinition {
    
    private System.Xml.XmlElement configField;
    
    private string contractField;
    
    private string serviceField;
    
    /// <remarks/>
    public System.Xml.XmlElement config {
        get {
            return this.configField;
        }
        set {
            this.configField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contract {
        get {
            return this.contractField;
        }
        set {
            this.contractField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
}
